[env:bare_metal_lora_tx]
platform = nordicnrf52
board = nrf52840_dk
build_flags =
    -nostartfiles
    -nostdlib
    -ffreestanding
    -mcpu=cortex-m4
    -mthumb
    -mfloat-abi=soft
build_unflags =
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
board_build.ldscript = linker.ld

debug_tool = jlink
upload_protocol = jlink
upload_flags =
    -SelectEmuBySN
    1050295470
